CREATE TABLE participants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login_id INT NOT NULL,
    image VARCHAR(255),
    prefix VARCHAR(255),
    fname VARCHAR(255) NOT NULL,
    lname VARCHAR(255),
    designation VARCHAR(255),
    gender VARCHAR(10),
    institute_name VARCHAR(255),
    address TEXT,
    city TEXT,
    pincode VARCHAR(20), -- Added pincode column
    district INT,
    state INT,
    country VARCHAR(255),
    mobile VARCHAR(20),
    mobile_verified TINYINT(1) DEFAULT 0,
    email VARCHAR(255) NOT NULL,
    email_verified TINYINT(1) DEFAULT 0,
    facebook VARCHAR(255),
    linkedin VARCHAR(255),
    twitter VARCHAR(255),
    orcid VARCHAR(255),
    biography TEXT,
    active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdby VARCHAR(255),
    updatedby VARCHAR(255),
    FOREIGN KEY (login_id) REFERENCES login(id) ON DELETE CASCADE
);
