CREATE TABLE registration (
    id INT AUTO_INCREMENT PRIMARY KEY,
    programme_id INT NOT NULL,
    participant_id INT NOT NULL,
    reg_type ENUM('1', '2') NOT NULL COMMENT '1-Individual, 2-Group',
    reg_group_name VARCHAR(255),
    accommodation ENUM('Yes', 'No'),
    category VARCHAR(50),
    passno VARCHAR(255),
    passv DATE,
    pob VARCHAR(255),
    nation VARCHAR(255),
    pno VARCHAR(255),
    pbank VARCHAR(255),
    pdate DATE,
    pamt VARCHAR(255),
    payment ENUM('1', '2') NOT NULL COMMENT '1-Offline, 2-Online',
    payment_verification ENUM('0', '1', '2', '3') DEFAULT '0' COMMENT '0-Unverified, 1-Verified, 2-Hold, 3-Reject',
    payment_remarks TEXT,
    acc_cat INT(3),
    acc_place ENUM('1', '2', '3', '4', '5') COMMENT '1-Univ, 2-L D, 3-IUCTE, 4-Yug, 5-Faculty',
    acc_roomno VARCHAR(255),
    acc_remarks TEXT,
    adate DATETIME,
    rdate DATETIME,
    mode VARCHAR(50),
    active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdby VARCHAR(255),
    updatedby VARCHAR(255),
    FOREIGN KEY (programme_id) REFERENCES programme(id) ON DELETE CASCADE,
    FOREIGN KEY (participant_id) REFERENCES participants(id) ON DELETE CASCADE
);